# -*- coding: utf-8 -*-
"""
A module to load processed GNSS measurements generated by RTKLib
(.pos files).

The GNSS latitude/longitude/height (LLH) measurements are converted to 
local planar XY coordinates relative to a LLH reference location. Tracks
also include planar speed and orientation derived from XY. 

As long as the track is not rotated (using trk.rotate_xy()), X equals East
and Y equals North, consistent with the ENU convention. The WGS84 reference
ellipsoid is used to convert LLH to local coordinates.  

Tracks include the following features:
    x : The x distance from the reference in meters. 
    y : The y distance from the reference in meters. 
    psi : The heading in radians with psi=0 in x-direction and psi in 
        [-np.pi, pi].
    v : The planar forward speed in meters/second.
    sdx : The standard deviation of the x-distance in meters.
    sdy : The standard deviation of the y-distance in meters.
    sdxy : The covariance between x and y-distance in meters^2
    sdv : A rough estimate of the standard deviation of the forward speed
        in m/s. Derived from sdx/sdy/sdxy assuming temporal independency.
    sdpsi : A rough estimate of the standard deviation of the heading
        in radians. Derived from sdx/sdy/sdxy assuming temporal independency.

@author: Christoph M. Konrad
"""
import os
import numpy as np
import pandas as pd
import datetime
import matplotlib.pyplot as plt
from trajdatamanager.datamanager import DataManager, Track, Sequence

# WGS84 constants
A_WGS84 = 6378137.0
F_WGS84 = 1 / 298.257223563
E2_WGS84 = F_WGS84 * (2 - F_WGS84)

class RTKLibGNSSManager(DataManager):
    """
    Manage .pos files with GNSS data generated by RTKLib
    """
    
    NUM_SKIP_ROWS = 24  # Number of rows to skip at the bginning of a .pos file
    T_S = 0.1  # Sample time

    def __init__(
        self,
        dir_data,
        reference_location=[None, None, None],
        sample_time = 0.1,
        num_skip_rows = None,
    ):
        """Create a DataManager to import .pos files generated by RTKLib

        Parameters
        ----------
        dir_data: str
            The root directory. 
        reference_location : list, optional
            The reference location (lat[deg], lon[deg], h[m]) for calculating local ENU (East/North/Up) coordinates.
            Any None in the list will be replaced by the first value of the .pos file. The default is [None, None, None], 
            i.e., all positions are relative to the start. The height h is interpreted as the
            ellipsoidal height of the WGS84 reference ellipsoid in meters. Visit https://www.unavco.org/software/
            geodetic-utilities/geoid-height-calculator/geoid-height-calculator.html to look up the 
            height above sea level of a desired reference location on the map.
        num_skip_rows : int, optional
            The number of header rows in the .pos file, by default 24.
        sample_time : float, optional
            The sample time (time between samples) in s. Default is 0.1 s.
        """
        super().__init__(dir_data)

        self.reference_location = reference_location
        self.dt = sample_time
        
        if num_skip_rows is None:
            self.num_skip_rows = self.NUM_SKIP_ROWS
        else:
            self.num_skip_rows = num_skip_rows
        
    def load_sequence(self):
        """Load a sequence of multiple .pos files in the data directory.

        Returns
        -------
        trajdatamanager.datamanager.Sequence
            Sequence of multiple tracks for all .pos files in the data
            directory.

        """
        
        tracks = []
        
        for path, folders, files in os.walk(self.dir):
            for f in files:
                if f[-4:] == ".pos":
                    tracks += self.load_tracks(f)
            
        return Sequence(tracks)

    def load_tracks(self, filename):
        """
        Load an individual track from a .pos file with the file name filename
        in the data directory.

        Parameters
        ----------
        filename : String
            Filepath of the .pos file relative to the root directory.

        Returns
        -------
        trajdatamanager.datamanager.Track
            A Track object storing the data in the .pos file.

        """

        # load .pos file
        df = self._read_pos_file(os.path.join(self.dir, filename))
        if df.shape[0] == 0:
            return []

        # xy positions
        x, y, _ = llh_to_enu(df['latitude(deg)'], df['longitude(deg)'], df['height(m)'], 
                             lat_ref=self.reference_location[0],
                             lon_ref=self.reference_location[1],
                             h_ref=self.reference_location[2])
        
        # measurement covariances
        sigma_x = df['sde(m)'].to_numpy(copy=True)
        sigma_y = df['sdn(m)'].to_numpy(copy=True)
        sigma_xy = df['sdne(m)'].to_numpy(copy=True)
        position_mode = df['Q'].to_numpy(copy=True)

        #inflate in float mode. This seems to often underestimate the error
        if np.any(position_mode==2):
            sigma_x[position_mode==2] = 0.3#np.minimum(0.5, sigma_x[position_mode==2]*100)
            sigma_y[position_mode==2] = 0.3#np.minimum(0.5, sigma_x[position_mode==2]*100)

        sigma_floor = 1e-6
        sigma_y = np.where(sigma_y==0, sigma_floor, sigma_y)
        sigma_x = np.clip(sigma_x, a_min=sigma_floor + sigma_xy**2/sigma_y, a_max=None) #Replace truncated values according to Cauchy-Schwartz bound
        sigma_y = np.clip(sigma_y, a_min=sigma_floor + sigma_xy**2/sigma_x, a_max=None)
        
        # time
        t = np.array([ti.to_pydatetime().replace(tzinfo=datetime.UTC) - datetime.timedelta(seconds=18) for ti in df["Timestamp"]])
        t_sec = np.array([(ti - t[0]).total_seconds() for ti in t], dtype=float)
        dt_true = float(np.median(np.diff(t_sec)))
        dt = self.dt

        if np.abs(dt_true - dt) > 10e-6:
            raise ValueError(f"The specified sample time {dt} s doesn't fit the data! Data has a median time between samples of {dt_true} s")

        # detect signal blocks
        t_full = dt * np.arange(int(round(t_sec[-1] / dt)) + 1)
        t_full_dt = [t[0] + datetime.timedelta(seconds=ts) for ts in t_full]
        positions = np.searchsorted(t_full, t_sec)

        block_mask = np.zeros(t_full.size)
        block_mask[positions] = 1
        start_blocks = np.argwhere(np.diff(block_mask) > 0).flatten()
        end_blocks = np.argwhere(np.diff(block_mask) < 0).flatten()

        if len(start_blocks) == 0:
            start_blocks = [0]
        if len(end_blocks) == 0:
            end_blocks = [t_full.size]
        if start_blocks[0] > end_blocks[0]:
            start_blocks = np.r_[0, start_blocks]
        if start_blocks[-1] > end_blocks[-1]:
            end_blocks = np.r_[end_blocks, t_full.size]

        # insert missing values
        def insert_nan(feat, value_positions):
            feat_out = np.full(t_full.size, np.nan, dtype=float)
            feat_out[value_positions] = feat
            return feat_out
        x = insert_nan(x, positions)
        y = insert_nan(y, positions)
        sigma_x = insert_nan(sigma_x, positions)
        sigma_y = insert_nan(sigma_y, positions)
        sigma_xy = insert_nan(sigma_xy, positions)

        # precompute variances
        sigma_x2 = sigma_x**2
        sigma_y2 = sigma_y**2
        sigma_xy2 = np.sign(sigma_xy) * sigma_xy**2

        # loop over blocks
        psi = np.full(t_full.size, np.nan, dtype=float)
        v = np.full(t_full.size, np.nan, dtype=float)
        sigma_psi = np.full(t_full.size, np.inf, dtype=float)
        sigma_v = np.full(t_full.size, np.inf, dtype=float)
        vx = np.full(t_full.size, np.nan, dtype=float)
        vy = np.full(t_full.size, np.nan, dtype=float)
        var_vx = np.full(t_full.size, np.nan, dtype=float)
        var_vy = np.full(t_full.size, np.nan, dtype=float)
        cov_vxvy = np.full(t_full.size, np.nan, dtype=float)

        for ia, io in zip(start_blocks, end_blocks):
            if io - ia < 3:
                continue

            xb = x[ia:io]
            yb = y[ia:io]

            # speed
            vxb = np.gradient(xb, dt, edge_order=2)[1:-1]
            vyb = np.gradient(yb, dt, edge_order=2)[1:-1]
            vb = np.hypot(vxb, vyb)

            # heading
            psib = np.arctan2(vyb, vxb)
            v2b = vb**2 + 1e-12

            # check for numerical errors in the covariance
            # must satisfy cov <= sqrt(var_x * var_y)
            var_vxb = (sigma_x2[ia:io][:-2] + sigma_x2[ia:io][2:]) / (4 * dt**2)
            var_vyb = (sigma_y2[ia:io][:-2] + sigma_y2[ia:io][2:]) / (4 * dt**2)
            cov_vxvyb = (sigma_xy2[ia:io][:-2] + sigma_xy2[ia:io][2:]) / (4 * dt**2)

            max_cov_v = np.sqrt(var_vxb * var_vyb)
            val = np.logical_and(cov_vxvyb < max_cov_v, cov_vxvyb >-max_cov_v)

            # calculate speed and heading standard deviation
            sigvb = np.full(var_vxb.size, np.inf)
            sigpsib = np.full(var_vxb.size, np.inf)

            sigvb[val] = np.sqrt((vxb[val]**2 * var_vxb[val] + vyb[val]**2 * var_vyb[val] + 2 * vxb[val] * vyb[val] * cov_vxvyb[val]) / v2b[val])
            sigpsib[val] = np.sqrt((vyb[val]**2 * var_vxb[val] + vxb[val]**2 * var_vyb[val] - 2 * vxb[val] * vyb[val] * cov_vxvyb[val]) / v2b[val]**2)

            # assing
            v[ia+1:io-1] = vb
            psi[ia+1:io-1] = psib

            sigma_v[ia+1:io-1] = sigvb
            sigma_psi[ia+1:io-1] = sigpsib

            vx[ia+1:io-1] = vxb
            vy[ia+1:io-1] = vyb

            var_vx[ia+1:io-1] = var_vxb
            var_vy[ia+1:io-1] = var_vyb
            cov_vxvy[ia+1:io-1] = cov_vxvyb

        #inflate variance due to independent sample assumption
        var_vx *= 6
        var_vx *= 6
        sigma_v *= 6
        sigma_psi *= 12
        
        # handle stationary parts
        moving = v > 0.5
        v = np.where(moving, v, np.nan)
        psi = np.where(moving, psi, np.nan)
        sigma_v = np.where(moving, sigma_v, np.inf)
        sigma_psi = np.where(moving, sigma_psi, np.inf)
        vx = np.where(moving, vx, np.nan)
        vy = np.where(moving, vy, np.nan)
        var_vx = np.where(moving, var_vx, np.nan)
        var_vy = np.where(moving, var_vy, np.nan)
        cov_vxvy = np.where(moving, cov_vxvy, np.nan)

        # create track
        data = np.c_[x, y, psi, v,  vx, vy,
                     sigma_x2, sigma_y2, sigma_xy2, 
                     sigma_v**2, sigma_psi**2,
                     var_vx, var_vy, cov_vxvy]

        keys = ["x", "y", "psi", "v", "vx" , "vy", "varx", "vary", "covxy", "varv", "varpsi", "varvx", "varvy", "covvxvy"]
        
        metadata = {'track_type': 'RTKLIBGNSSData',
                    'reference_location': self.reference_location,
                    'projection': 'ENU(WGS84)',
                    'source': os.path.join(self.dir, filename)
                    }

        trk = RTKLibGNSSTrack(
            filename, 2, t_full_dt, data, yaw_feature_index=2, data_feature_keys=keys,
            metadata=metadata
        )

        #trk.plot_uncertainties()

        return [trk]
    
    def _read_pos_file(self, filepath):
        """ Read the RTKlib .pos file into a DataFrame

        Parameters
        ----------
        filepath : str
            The filepath of the .pos file. 

        Returns
        -------
        df : pandas.DataFrame
            A DataFrame representing the data in a table. Contains the timestamp in a column called "Timestamp" and positions in columns called "longitude(deg)", "latitude(deg)".
        """

        df = pd.read_table(
            filepath,
            sep=r"\s+",
            skiprows=self.num_skip_rows,
        )
        df['Timestamp'] = pd.to_datetime(df[["%", "GPST"]].astype(str).agg(" ".join, axis=1))

        return df
    

class RTKLibGNSSTrack(Track):
    """A track object representing RTKLib GNSS measurements, which include
    position covariances.
    """
    def __init__(self,  *args, **kwargs):
        super().__init__(*args, **kwargs)

        # x, y and vx/vy are required to describe the position and orientation. psi and v can be derived. 
        # Better to represent orientation as velocity vector then as psi to tackle the discontinuities. 
        required_features = set(["x", "y", "vx", "vy", "varx", "vary", "covxy", "varvx", "varvy", "covvxvy"])
        if not required_features.issubset(set(self.data_feature_keys)):
            msg = (f"A RTKLibGNSSTrack requires at least the features {required_features}. Instead,"
                   f"you tried to create a Track object with the features {set(self.data_feature_keys)}")
            raise ValueError(msg)


    def get_position_covariance(self, time_index=None):
        """Get the position (X, Y) covariance matrix at a given indes. 

        This requires sdx, sdy, and sdz features in the track object. 
        Tracks loaded by datamanager.RTKLIBdatamanager have these features.

        If the track has not been rotated or shifted, XY equals EN (East/North)
        relative to the reference location. The Z (Up) component is ignored.

        Parameters
        ----------
        trk : datamanager.RTKLibTrack
            The track object to get the covariance from. 
        time_index : int, optional
            The time step. If not given, return the trajectory of 
            covariance matrices.

        Returns
        -------
        covariance : array
            The 2x2 XY covariance matrix at time_index or the
            2x2xN stack of covariances for all times. 
        """
        if time_index is None:
            cov = np.stack([self['varx'], self['covxy'], self['covxy'], self['vary']], axis=1)
            cov = cov.reshape(self.n, 2, 2)
        else:
            cov = np.array([[self['varx'][time_index], self['covxy'][time_index]],
                            [self['covxy'][time_index], self['vary'][time_index]],])
        return cov
    

    def get_velocity_covariance(self, time_index=None):
        """Get the velocity (vx, vy) covariance matrix at a given indes. 

        This requires varvx, varvy, and covvxvy features in the track object. 
        Tracks loaded by datamanager.RTKLIBdatamanager have these features.

        If the track has not been rotated or shifted, XY equals EN (East/North)
        relative to the reference location. The Z (Up) component is ignored.

        Parameters
        ----------
        trk : datamanager.RTKLibTrack
            The track object to get the covariance from. 
        time_index : int, optional
            The time step. If not given, return the trajectory of 
            covariance matrices.

        Returns
        -------
        covariance : array
            The 2x2 XY covariance matrix at time_index or the
            2x2xN stack of covariances for all times. 
        """
        if time_index is None:
            cov = np.stack([self['varvx'], self['covvxvy'], self['covvxvy'], self['varvy']], axis=1)
            cov = cov.reshape(self.n, 2, 2)
        else:
            cov = np.array([[self['varvx'][time_index], self['covvxvy'][time_index]],
                            [self['covvxvy'][time_index], self['varvy'][time_index]],])
        return cov
    

    def set_position_covariance(self, cov, time_index=None):
        """Set the covariances at a given time to a specific value.

        Parameters
        ----------
        cov : array
            2x2 or 2x2xN covariance 
        time_index : int, optional
            The time index to set a specific covariance. If None, 
            the covariances for all times are set and cov must be 2x2xN. 
            By default None
        """
        if time_index is None:
            self['varx'] = cov[:,0,0]
            self['vary'] = cov[:,1,1]
            self['covxy'] = cov[:,0,1]
        else:
            if cov.ndim == 3:
                cov = cov[time_index,:,:]
            self['varx'][time_index] = cov[0,0]
            self['vary'][time_index] = cov[1,1]
            self['covxy'][time_index] = cov[0,1]


    def set_velocity_covariance(self, cov, time_index=None):
        """Set the covariances at a given time to a specific value.

        Parameters
        ----------
        cov : array
            2x2 or 2x2xN covariance 
        time_index : int, optional
            The time index to set a specific covariance. If None, 
            the covariances for all times are set and cov must be 2x2xN. 
            By default None
        """
        if time_index is None:
            self['varvx'] = cov[:,0,0]
            self['varvy'] = cov[:,1,1]
            self['covvxvy'] = cov[:,0,1]
        else:
            if cov.ndim == 3:
                cov = cov[time_index,:,:]
            self['varvx'][time_index] = cov[0,0]
            self['varvy'][time_index] = cov[1,1]
            self['covvxvy'][time_index] = cov[0,1]


    def rotate_xy(self, alpha, deg=False):
        """Rotate a track in the xy plane

        This requires the track to have the features 'x' and 'y'. Any
        orientation feature should be named 'psi' to be rotated accordingly.        

        Parameters
        ----------
        alpha : float
            Rotation angle in rad (deg=False) or deg (deg=True).
        deg : bool, optional
            If true, alpha is interpreted in degrees. The default is False.

        Returns
        -------
        None.

        """
        if deg:
            alpha = alpha/180 * np.pi

        cosalpha = np.cos(alpha)
        sinalpha = np.sin(alpha)

        R = np.array([[cosalpha, -sinalpha], [sinalpha, cosalpha]])
        
        cov_pos = self.get_position_covariance()
        cov_pos = R @ cov_pos @ R.T
        self.set_position_covariance(cov_pos)

        cov_vel = self.get_velocity_covariance()
        cov_vel = R @ cov_vel @ R.T
        self.set_velocity_covariance(cov_vel)

        super().rotate_xy(alpha, False)

    def plot_uncertainties(self):
        
        fig, axes = plt.subplots(6,1, sharex=True, layout='constrained')
        
        features = ['x', 'y', 'psi', 'v', 'vx', 'vy']
        self.plot(axes=axes, features=features, plot_over_timestamps=True)

        for ax, feat in zip(axes, features):
            sigma = np.sqrt(self[f'var{feat}']) 
            ax.fill_between(self.t, self[feat]-sigma, self[feat]+sigma, alpha=0.2, where=np.isfinite(self['varx']))
            ax.set_label(feat)
        axes[0].set_title(self.track_id)
        axes[-1].set_label('t')

        return fig, axes


def llh_to_ecef(lat, lon, h):
    """ Convert latitude, longitude [deg] and height [m]
    to ECEF XYZ [m]


    Parameters
    ---------
    lat : array-like
        Latitude in degrees
    lon : array-like
        Longitude in degrees
    h : array-like
        Ellipsoidal height in meters (WGS-84)
    
    Returns
    ---------
    X : array
        X component of ECEF in m.
    Y : array
        Y component of ECEF in m.
    Z : array
        Z component of ECEF in m.
    """
    lat = np.deg2rad(lat)
    lon = np.deg2rad(lon)

    sin_lat = np.sin(lat)
    cos_lat = np.cos(lat)
    sin_lon = np.sin(lon)
    cos_lon = np.cos(lon)

    N = A_WGS84 / np.sqrt(1 - E2_WGS84 * sin_lat**2)

    X = (N + h) * cos_lat * cos_lon
    Y = (N + h) * cos_lat * sin_lon
    Z = (N * (1 - E2_WGS84) + h) * sin_lat

    return X, Y, Z


def ecef_to_enu(dx, dy, dz, lat_ref, lon_ref):
    """ Convert ECEF delta vector to ENU at reference point.

    Parameters
    ---------
    dx : array-like
        Distance in ECEF X-direction.
    dy : array-like
        Distance in ECEF Y-direction.
    dz : array-like
        Distance in ECEF Z-direction.
    lat_ref : float
        Latitude of the reference location in degrees.  
    lon_ref : float
        Longitude of the reference loaction in degrees.
    
    Returns
    ---------
    E : array
        Offset to the east of the reference point in m
    N : array
        Offset to the north of the reference point in m
    U : array
        Offset above the reference point in m
    """
    lat_ref = np.deg2rad(lat_ref)
    lon_ref = np.deg2rad(lon_ref)

    sin_lat = np.sin(lat_ref)
    cos_lat = np.cos(lat_ref)
    sin_lon = np.sin(lon_ref)
    cos_lon = np.cos(lon_ref)

    E = -sin_lon * dx + cos_lon * dy
    N = -sin_lat * cos_lon * dx - sin_lat * sin_lon * dy + cos_lat * dz
    U =  cos_lat * cos_lon * dx + cos_lat * sin_lon * dy + sin_lat * dz

    return E, N, U


def llh_to_enu(lat, lon, h, lat_ref=None, lon_ref=None, h_ref=None):
    """Convert llh (Latitude/Longitude/Height) measurements from 
    RTKLib .pos files to ENU (East/North/Up) offset to a given reference 
    location. 

    Parameters
    ----------
    lat : array-like
        Latitude in degrees
    long : array-like
        Longitude in degrees
    h : array-like
        Height in m
    lat_ref : float, optional
        Latitude of the reference location in degrees. If not given, 
        take the first value of lat.
    long_ref : float. optional
        Longitude of the reference location in degrees. If not given, 
        take the first value of lon.
    h_ref : float, optional
        Ellipsoidal height of the reference location in meters (WGS-84). If not given, 
        take the first value of h.

    Returns
    ---------
    E : array
        Offset to the east of the reference point in m
    N : array
        Offset to the north of the reference point in m
    U : array
        Offset above the reference point in m
    """

    if lat_ref is None:
        lat_ref = lat[0]
    if lon_ref is None:
        lon_ref = lon[0]
    if h_ref is None:
        h_ref = h[0]

    X, Y, Z = llh_to_ecef(lat, lon, h)
    X_ref, Y_ref, Z_ref = llh_to_ecef(lat_ref, lon_ref, h_ref)

    return ecef_to_enu(X-X_ref, Y-Y_ref, Z-Z_ref, lat_ref, lon_ref)


def is_psd(M, tol=1e-12):
    """
    Check if a real symmetric matrix is positive semidefinite (PSD).

    Parameters
    ----------
    M : np.ndarray
        Square matrix (n x n). Will be symmetrized before the check.
    tol : float
        Numerical tolerance. Eigenvalues >= -tol are treated as non-negative.

    Returns
    -------
    ok : bool
        True if PSD within tolerance.
    min_eig : float
        Minimum eigenvalue (after symmetrization).
    """
    M = 0.5 * (M + M.T)  # symmetrize to remove tiny asymmetries
    w = np.linalg.eigvalsh(M)
    return np.all(w >= -tol), float(w.min())
