# -*- coding: utf-8 -*-
"""
A module to load processed GNSS measurements generated by RTKLib
(.pos files).

The GNSS latitude/longitude/height (LLH) measurements are converted to 
local planar XY coordinates relative to a LLH reference location. Tracks
also include planar speed and orientation derived from XY. 

As long as the track is not rotated (using trk.rotate_xy()), X equals East
and Y equals North, consistent with the ENU convention. The WGS84 reference
frame is used to convert LLH to local coordinates.  

Tracks include the following features:
    x : The x distance from the reference in meters. 
    y : The y distance from the reference in meters. 
    psi : The heading in radians with psi=0 in x-direction and psi in 
        [-np.pi, pi].
    v : The planar forward speed in meters/second.
    sdx : The standard deviation of the x-distance in meters.
    sdy : The standard deviation of the y-distance in meters.
    sdxy : The covariance between x and y-distance in meters^2
    sdv : A rough estimate of the standard deviation of the forward speed
        in m/s. Derived from sdx/sdy/sdxy assuming temporal independency.
    sdpsi : A rough estimate of the standard deviation of the heading
        in radians. Derived from sdx/sdy/sdxy assuming temporal independency.

@author: Christoph M. Konrad
"""
import os
import numpy as np
import pandas as pd
from trajdatamanager.datamanager import DataManager, Track, Sequence

# WGS84 constants
A_WGS84 = 6378137.0
F_WGS84 = 1 / 298.257223563
E2_WGS84 = F_WGS84 * (2 - F_WGS84)

class RTKLibGNSSManager(DataManager):
    """
    Manage .pos files with GNSS data generated by RTKLib
    """
    
    NUM_SKIP_ROWS = 24  # Number of rows to skip at the bginning of a .pos file
    T_S = 0.1  # Sample time

    def __init__(
        self,
        dir_data,
        reference_location=[None, None, None],
        num_skip_rows = None,
    ):
        """Create a DataManager to import .pos files generated by RTKLib

        Parameters
        ----------
        dir_data: str
            The root directory. 
        reference_location : list, optional
            The reference location [lat(deg), lon(deg), h(m)] for calculating local ENU (East/North/Up) coordinates.
            Any None in the list will be replaced by the first value of the .pos file. The default is [None, None, None], 
            i.e., all positions are relative to the start.
        num_skip_rows : int, optional
            The number of header rows in the .pos file, by default 24.
        """
        super().__init__(dir_data)

        self.reference_location = reference_location
        
        if num_skip_rows is None:
            self.num_skip_rows = self.NUM_SKIP_ROWS
        else:
            self.num_skip_rows = num_skip_rows
        
    def load_sequence(self):
        """Load a sequence of multiple .pos files in the data directory.

        Returns
        -------
        trajdatamanager.datamanager.Sequence
            Sequence of multiple tracks for all .pos files in the data
            directory.

        """
        
        tracks = []
        
        for path, folders, files in os.walk(self.dir):
            for f in files:
                if f[-4:] == ".pos":
                    tracks += self.load_tracks(f)
            
        return Sequence(tracks)

    def load_tracks(self, filename):
        """
        Load an individual track from a .pos file with the file name filename
        in the data directory.

        Parameters
        ----------
        filename : String
            Filepath of the .pos file relative to the root directory.

        Returns
        -------
        trajdatamanager.datamanager.Track
            A Track object storing the data in the .pos file.

        """

        df = self._read_pos_file(os.path.join(self.dir, filename))

        if df.shape[0] == 0:
            return []

        x, y, z = llh_to_enu(df['latitude(deg)'], df['longitude(deg)'], df['height(m)'], 
                             lat_ref=self.reference_location[0],
                             lon_ref=self.reference_location[1],
                             h_ref=self.reference_location[2])
        
        # time
        t = df["Timestamp"]
        t = np.array([ti.to_pydatetime().replace(tzinfo=dt.UTC) - dt.timedelta(seconds=18) for ti in t])
        t_sec = np.array([(ti - t[0]).total_seconds() for ti in t], dtype=float)
        dt = float(np.median(np.diff(t_sec)))

        # measurement covariances
        sigma_x2 = df['sde(m)'].to_numpy()**2
        sigma_y2 = df['sdn(m)'].to_numpy()**2
        sigma_xy = df['sdne(m)'].to_numpy()

        # detect signal blocks
        t_full = dt * np.arange(int(t_sec[-1] / dt) + 1)
        positions = np.searchsorted(t_full, t_sec)

        block_mask = np.zeros(t_full.size, dtype=bool)
        block_mask[positions] = True
        start_blocks = np.argwhere(np.diff(block_mask) > 0).flatten()
        end_blocks = np.argwhere(np.diff(block_mask) < 0).flatten()

        if start_blocks[0] > end_blocks[0]:
            start_blocks = np.r_[0, start_blocks]
        if start_blocks[-1] > end_blocks[-1]:
            end_blocks = np.r_[end_blocks, t_full.size]

        psi = np.full(t_full.size, np.nan, dtype=float)
        v = np.full(t_full.size, np.nan, dtype=float)
        sigma_psi = np.full(t_full.size, np.inf, dtype=float)
        sigma_v = np.full(t_full.size, np.inf, dtype=float)

        for ia, io in zip(start_blocks, end_blocks):
            if io - ia < 3:
                continue

            tb = t_sec[ia:io]
            xb = x[ia:io]
            yb = y[ia:io]

            dt = float(np.median(np.diff(tb)))

            # speed
            vxb = np.gradient(xb, dt, edge_order=2)[1:-1]
            vyb = np.gradient(yb, dt, edge_order=2)[1:-1]
            vb = np.hypot(vxb, vyb)

            # heading
            psib = np.arctan2(vyb, vxb)
            v2b = vb**2 + 1e-12

            var_vx = (sigma_x2[ia:io][:-2] + sigma_x2[ia:io][2:]) / (4 * dt**2)
            var_vy = (sigma_y2[ia:io][:-2] + sigma_y2[ia:io][2:]) / (4 * dt**2)
            cov_vxvy = (sigma_xy[ia:io][:-2] + sigma_xy[ia:io][2:]) / (4 * dt**2)

            sigvb = np.sqrt((vxb**2 * var_vx + vyb**2 * var_vy + 2 * vxb * vyb * cov_vxvy) / v2b)
            sigpsib = np.sqrt((vyb**2 * var_vx + vxb**2 * var_vy - 2 * vxb * vyb * cov_vxvy) / v2b**2)

            # assing
            v[ia+1:io-1] = vb
            psi[ia+1:io-1] = psib

            sigma_v[ia+1:io-1] = sigvb
            sigma_psi[ia+1:io-1] = sigpsib

        # inflate variance due to independent sample assumption
        #sigma_v *= 3
        #sigma_psi *= 5
        
        # handle stationary parts
        moving = v > 3 * sigma_v
        v = np.where(moving, v, np.nan)
        psi = np.where(moving, psi, np.nan)
        sigma_v = np.where(moving, sigma_v, np.inf)
        sigma_psi = np.where(moving, sigma_psi, np.inf)

        # create track
        data = np.c_[x, y, psi, v,  
                     df['sde(m)'].to_numpy(), df['sdn(m)'].to_numpy(), df['sdne(m)'].to_numpy(), 
                     sigma_v, sigma_psi]

        keys = ["x", "y", "psi", "v", "sdx", "sdy", "sdz", "sdxy", "sdv", "sdpsi"]
        
        metadata = {'track_type': 'RTKLIBGNSSData',
                    'reference_location': self.reference_location,
                    'projection': 'ENU(WGS84)',
                    'source': os.path.join(self.dir, filename)
                    }

        trk = self.track_type(
            filename, 2, t, data, yaw_feature_index=2, data_feature_keys=keys,
            metadata=metadata
        )

        return [trk]
    
    def _read_pos_file(self, filepath):
        """ Read the RTKlib .pos file into a DataFrame

        Parameters
        ----------
        filepath : str
            The filepath of the .pos file. 

        Returns
        -------
        df : pandas.DataFrame
            A DataFrame representing the data in a table. Contains the timestamp in a column called "Timestamp" and positions in columns called "longitude(deg)", "latitude(deg)".
        """

        df = pd.read_table(
            filepath,
            sep=r"\s+",
            parse_dates={"Timestamp": [0, 1]},
            skiprows=self.num_skip_rows,
        )

        return df
    

class RTKLibGNSSTrack(Track):
    """A track object representing RTKLib GNSS measurements, which include
    position covariances.
    """
    def __init__(self,  *args, **kwargs):
        super().__init__(*args, **kwargs)

        required_features = set(["x", "y", "psi", "v", "sdx", "sdy", "sdz", "sdxy", "sdv", "sdpsi"])
        if not set(self.data_feature_keys).issubset(required_features):
            msg = (f"A RTKLibGNSSTrack requires at least the features {required_features}. Instead,"
                   f"you tried to create a Track object with the features {set(self.data_feature_keys)}")
            raise ValueError(msg)


    def get_position_covariance(self, time_index=None):
        """Get the position (X, Y) covariance matrix at a given indes. 

        This requires sdx, sdy, and sdz features in the track object. 
        Tracks loaded by datamanager.RTKLIBdatamanager have these features.

        If the track has not been rotated or shifted, XY equals EN (East/North)
        relative to the reference location. The Z (Up) component is ignored.

        Parameters
        ----------
        trk : datamanager.RTKLibTrack
            The track object to get the covariance from. 
        time_index : int, optional
            The time step. If not given, return the trajectory of 
            covariance matrices.

        Returns
        -------
        covariance : array
            The 2x2 XY covariance matrix at time_index or the
            2x2xN stack of covariances for all times. 
        """
        if time_index is None:
            cov = np.stack([self['sdx']**2, self['sdxy'], 
                           [self['sdxy'], self['sdy']**2]])
            cov = cov.reshape(2,2,self.n)
        else:
            cov = np.array([[self['sdx'][time_index]**2, self['sdxy'][time_index]],
                            [self['sdxy'][time_index], self['sdy'][time_index]**2],])
        return cov
    
    def set_position_covariance(self, cov, time_index=None):
        """Set the covariances at a given time to a specific value.

        Parameters
        ----------
        cov : array
            2x2 or 2x2xN covariance 
        time_index : int, optional
            The time index to set a specific covariance. If None, 
            the covariances for all times are set and cov must be 2x2xN. 
            By default None
        """
        if time_index is None:
            self['sdx'] = np.sqrt(cov[0,0,:])
            self['sdy'] = np.sqrt(cov[1,1,:])
            self['sdxy'] = cov[0,1,:]
        else:
            if cov.ndim == 3:
                cov = cov[:,:,time_index]
            self['sdx'][time_index] = np.sqrt(cov[0,0])
            self['sdy'][time_index] = np.sqrt(cov[1,1])
            self['sdxy'][time_index] = cov[0,1]

    def rotate_xy(self, alpha, deg=False):
        """Rotate a track in the xy plane

        This requires the track to have the features 'x' and 'y'. Any
        orientation feature should be named 'psi' to be rotated accordingly.        

        Parameters
        ----------
        alpha : float
            Rotation angle in rad (deg=False) or deg (deg=True).
        deg : bool, optional
            If true, alpha is interpreted in degrees. The default is False.

        Returns
        -------
        None.

        """
        if deg:
            alpha = alpha/180 * np.pi

        cosalpha = np.cos(alpha)
        sinalpha = np.sin(alpha)

        R = np.array([[cosalpha, -sinalpha],
                       sinalpha, cosalpha])
        
        cov = self.get_position_covariance()
        cov = R @ cov @ R.T

        self.set_position_covariance(cov)

        super().rotate_xy(alpha, deg)


def llh_to_ecef(lat, lon, h):
    """ Convert latitude, longitude [deg] and height [m]
    to ECEF XYZ [m]


    Parameters
    ---------
    lat : array-like
        Latitude in degrees
    lon : array-like
        Longitude in degrees
    h : array-like
        Ellipsoidal height in meters (WGS-84)
    
    Returns
    ---------
    X : array
        X component of ECEF in m.
    Y : array
        Y component of ECEF in m.
    Z : array
        Z component of ECEF in m.
    """
    lat = np.deg2rad(lat)
    lon = np.deg2rad(lon)

    sin_lat = np.sin(lat)
    cos_lat = np.cos(lat)
    sin_lon = np.sin(lon)
    cos_lon = np.cos(lon)

    N = A_WGS84 / np.sqrt(1 - E2_WGS84 * sin_lat**2)

    X = (N + h) * cos_lat * cos_lon
    Y = (N + h) * cos_lat * sin_lon
    Z = (N * (1 - E2_WGS84) + h) * sin_lat

    return X, Y, Z


def ecef_to_enu(dx, dy, dz, lat_ref, lon_ref):
    """ Convert ECEF delta vector to ENU at reference point.

    Parameters
    ---------
    dx : array-like
        Distance in ECEF X-direction.
    dy : array-like
        Distance in ECEF Y-direction.
    dz : array-like
        Distance in ECEF Z-direction.
    lat_ref : float
        Latitude of the reference location in degrees.  
    lon_ref : float
        Longitude of the reference loaction in degrees.
    
    Returns
    ---------
    E : array
        Offset to the east of the reference point in m
    N : array
        Offset to the north of the reference point in m
    U : array
        Offset above the reference point in m
    """
    lat_ref = np.deg2rad(lat_ref)
    lon_ref = np.deg2rad(lon_ref)

    sin_lat = np.sin(lat_ref)
    cos_lat = np.cos(lat_ref)
    sin_lon = np.sin(lon_ref)
    cos_lon = np.cos(lon_ref)

    E = -sin_lon * dx + cos_lon * dy
    N = -sin_lat * cos_lon * dx - sin_lat * sin_lon * dy + cos_lat * dz
    U =  cos_lat * cos_lon * dx + cos_lat * sin_lon * dy + sin_lat * dz

    return E, N, U


def llh_to_enu(lat, lon, h, lat_ref=None, lon_ref=None, h_ref=None):
    """Convert llh (Latitude/Longitude/Height) measurements from 
    RTKLib .pos files to ENU (East/North/Up) offset to a given reference 
    location. 

    Parameters
    ----------
    lat : array-like
        Latitude in degrees
    long : array-like
        Longitude in degrees
    h : array-like
        Height in m
    lat_ref : float, optional
        Latitude of the reference location in degrees. If not given, 
        take the first value of lat.
    long_ref : float. optional
        Longitude of the reference location in degrees. If not given, 
        take the first value of lon.
    h_ref : float, optional
        Ellipsoidal height of the reference location in meters (WGS-84). If not given, 
        take the first value of h.

    Returns
    ---------
    E : array
        Offset to the east of the reference point in m
    N : array
        Offset to the north of the reference point in m
    U : array
        Offset above the reference point in m
    """

    if lat_ref is None:
        lat_ref = lat[0]
    if lon_ref is None:
        lon_ref = lon[0]
    if h_ref is None:
        h_ref = h[0]

    X, Y, Z = llh_to_ecef(lat, lon, h)
    X_ref, Y_ref, Z_ref = llh_to_ecef(lat_ref, lon_ref, h_ref)

    return ecef_to_enu(X-X_ref, Y-Y_ref, Z-Z_ref, lat_ref, lon_ref)

